# Generated by Django 2.2 on 2020-03-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200327_1746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_posts',
        ),
    ]
