# Generated by Django 2.2 on 2020-03-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200327_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group',
            new_name='group_posts',
        ),
    ]
