# Generated by Django 2.2 on 2020-03-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200327_1750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author_posts',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='group_posts',
            new_name='group',
        ),
    ]
